name: Remote SSH Test
on: workflow_dispatch
jobs:
  hello-world:
    name: Test SSH Connection
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh and echoing hello world
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 2222
          script: echo "Hello World!"
  postman:
    name: Test Backend Endpoints with Postman
    runs-on: ubuntu-latest
    steps:
      - name: run postman tests
        uses: matt-ball/newman-action@master
        with:
          collection: Component-testing.postman_collection.json
