on:
  workflow_dispatch:
jobs:
  say-hello-world:
    runs-on: ubuntu-22.04
    steps:
      - name: executing remote ssh commands using password
        uses: Neslihan-Avsar/uek_223-gruppe-4-backend @ main
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 2222
          script: echo “Hello World”
